#!/usr/bin/env bash
# Fixes the issue with the server
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/ngnix/ngnix.conf
pkill apache2
sudo -u nginx service nginx restart
